export const INSIGHT_DRAFT_UPDATE = '[insight] DRAFT_UPDATE'
export const INSIGHT_DRAFT_UPDATE_SUCCESS = '[insight] DRAFT_UPDATE_SUCCESS'
export const INSIGHT_DRAFT_UPDATE_FAILED = '[insight] DRAFT_UPDATE_FAIL'
export const INSIGHT_DRAFT_UPDATE_DATA_WIPE = '[insight] DRAFT_UPDATE_DATA_WIPE'
