export const INSIGHT_DRAFT_PUBLISH = '[insight] DRAFT_PUBLISH'
export const INSIGHT_DRAFT_PUBLISH_SUCCESS = '[insight] DRAFT_PUBLISH_SUCCESS'
export const INSIGHT_DRAFT_PUBLISH_FAILED = '[insight] DRAFT_PUBLISH_FAILED'

export const INSIGHT_DRAFT_UPDATE = '[insight] DRAFT_UPDATE'
export const INSIGHT_DRAFT_UPDATE_SUCCESS = '[insight] DRAFT_UPDATE_SUCCESS'
export const INSIGHT_DRAFT_UPDATE_FAILED = '[insight] DRAFT_UPDATE_FAIL'
export const INSIGHT_DRAFT_UPDATE_DATA_WIPE = '[insight] DRAFT_UPDATE_DATA_WIPE'
