// trends
export const TRENDS_HYPED_FETCH = '[trends] HYPED_FETCH'
export const TRENDS_HYPED_FETCH_SUCCESS = '[trends] HYPED_FETCH_SUCCESS'
export const TRENDS_HYPED_FETCH_FAILED = '[trends] HYPED_FETCH_FAILED'
export const TRENDS_HYPED_WORD_SELECTED = '[trends] HYPED_WORD_SELECTED'
// tickers + slugs
export const TRENDS_HYPED_FETCH_TICKERS_SLUGS =
  '[trends] HYPED_FETCH_TICKERS_SLUGS'
export const TRENDS_HYPED_FETCH_TICKERS_SLUGS_SUCCESS =
  '[trends] HYPED_FETCH_TICKERS_SLUGS_SUCCESS'
export const TRENDS_HYPED_FETCH_TICKERS_SLUGS_FAILED =
  '[trends] HYPED_FETCH_TICKERS_SLUGS_FAILED'

export const TREND_WORD_SCORE_CHANGE_FETCH =
  '[trends] TREND_WORD_SCORE_CHANGE_FETCH'
export const TREND_WORD_SCORE_CHANGE_FULFILLED =
  '[trends] WORD_SCORE_CHANGE_FULFILLED'
export const TREND_WORD_SCORE_CHANGE_FAILED =
  '[trends] WORD_SCORE_CHANGE_FAILED'

export const TREND_WORD_VOLUME_CHANGE_FETCH =
  '[trends] WORD_VOLUME_CHANGE_FETCH'
export const TREND_WORD_VOLUME_CHANGE_FULFILLED =
  '[trends] WORD_VOLUME_CHANGE_FULFILLED'
export const TREND_WORD_VOLUME_CHANGE_FAILED =
  '[trends] WORD_VOLUME_CHANGE_FAILED'

export const TRENDS_CONNECTED_WORDS_SUCCESS = '[trends] CONNECTED_WORDS_SUCCESS'
export const TRENDS_CONNECTED_WORDS_FAILED = '[trends] CONNECTED_WORDS_FAILED'
export const TRENDS_CONNECTED_WORDS_OPTIMIZATION_SUCCESS =
  '[trends] CONNECTED_WORDS_OPTIMIZATION_SUCCESS'
