// trends
export const TRENDS_HYPED_FETCH = '[trends] HYPED_FETCH'
export const TRENDS_HYPED_FETCH_SUCCESS = '[trends] HYPED_FETCH_SUCCESS'
export const TRENDS_HYPED_FETCH_FAILED = '[trends] HYPED_FETCH_FAILED'
export const TRENDS_HYPED_WORD_SELECTED = '[trends] HYPED_WORD_SELECTED'
