# ---- Base Node ----
FROM node:13.12-alpine AS base
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
ARG GIT_HEAD
RUN GIT_HEAD=$GIT_HEAD
WORKDIR /opt
COPY package.json package-lock.json* ./
COPY . /opt

# Stage: Building
FROM base AS builder
RUN apk --no-cache add git
# Install library dependencies
RUN if [ "$CI" = "true" ] ; then npm ci --only=prod; else npm i; fi
RUN npx patch-package

# Stage: Execution
FROM base
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
COPY --from=builder /opt/node_modules /opt/node_modules
