export const WORDCLOUD_CONTEXT_FETCH = '[wordCloud] CONTEXT_FETCH'
export const WORDCLOUD_CONTEXT_FETCH_CANCEL = '[wordCloud] CONTEXT_FETCH_CANCEL'
export const WORDCLOUD_CONTEXT_FETCH_SUCCESS =
  '[wordCloud] CONTEXT_FETCH_SUCCESS'
export const WORDCLOUD_CONTEXT_FETCH_FAILED = '[wordCloud] CONTEXT_FETCH_FAILED'
