export const MARKET_SEGMENTS_FETCH = `[app] MARKET_SEGMENTS_FETCH`
export const MARKET_SEGMENTS_FETCH_SUCCESS = `[app] MARKET_SEGMENTS_FETCH_SUCCESS`
export const MARKET_SEGMENTS_FETCH_FAIL = `[app] MARKET_SEGMENTS_FETCH_FAIL`
