// settings / account
export const SETTINGS_GENERATE_TELEGRAM_DEEP_LINK =
  '[settings] GENERATE_TELEGRAM_DEEP_LINK'
export const SETTINGS_REVOKE_TELEGRAM_DEEP_LINK =
  '[settings] REVOKE_TELEGRAM_DEEP_LINK'
export const SETTINGS_GENERATE_TELEGRAM_DEEP_LINK_SUCCESS =
  '[settings] GENERATE_TELEGRAM_DEEP_LINK_SUCCESS'
export const SETTINGS_GENERATE_TELEGRAM_DEEP_LINK_FAILED =
  '[settings] GENERATE_TELEGRAM_DEEP_LINK_FAILED'
export const SETTINGS_TOGGLE_NOTIFICATION_CHANNEL =
  '[settings] TOGGLE_NOTIFICATION_CHANNEL'
export const SETTINGS_TOGGLE_NOTIFICATION_CHANNEL_SUCCESS =
  '[settings] TOGGLE_NOTIFICATION_CHANNEL_SUCCESS'
export const SETTINGS_TOGGLE_NOTIFICATION_CHANNEL_FAILED =
  '[settings] TOGGLE_NOTIFICATION_CHANNEL_FAILED'
