// settings / account
export const SETTINGS_GENERATE_TELEGRAM_DEEP_LINK =
  '[settings] GENERATE_TELEGRAM_DEEP_LINK'
export const SETTINGS_GENERATE_TELEGRAM_DEEP_LINK_SUCCESS =
  '[settings] GENERATE_TELEGRAM_DEEP_LINK_SUCCESS'
export const SETTINGS_GENERATE_TELEGRAM_DEEP_LINK_FAILED =
  '[settings] GENERATE_TELEGRAM_DEEP_LINK_FAILED'
