export const TOP_HOLDERS_PANE = 'TOP_HOLDERS_PANE'
export const METRICS_EXPLANATION_PANE = 'METRICS_EXPLANATION_PANE'
export const SPENT_COIN_COST = 'SPENT_COIN_COST'
export const SOCIAL_CONTEXT = 'SOCIAL_CONTEXT'
