export const PATHS = {
  FEED: '/feed',
  SOCIAL_TOOl: '/labs/trends/explore/',
  LOGIN: '/login',
  LOGIN_VIA_EMAIL: '/login/email',
  CREATE_ACCOUNT: '/sign-up',
  GDPR: '/gdpr',
  PRO_METRICS: '/pro-sheets-templates',
  INDEX: '/',
  STUDIO: '/studio',
  CHARTS: '/charts',
  STABLECOINS: '/stablecoins',
  ETH2: '/eth2',
  ETH_ANALYSIS: '/eth-analysis',
  UNISWAP_PROTOCOL: '/uniswap-protocol',
  SHEETS_TEMPLATES: '/sheets/daa-vs-price',
  LABELS: '/labels',
  DEXS: '/decentralized-exchanges',
  BTC_LOCKED: '/bitcoin-locked-on-ethereum',
  ADDRESSES_WATCHLIST: '/watchlist/addresses',
  SCREENER: '/screener'
}
