export const METRIC = 'METRIC'
export const WIDGET = 'WIDGET'
export const CONNECTED_WIDGET = 'CONNECTED_WIDGET'
export const SIDEPANEL = 'SIDEPANEL'
export const ICO_PRICE = 'ICO_PRICE'
export const INSIGHT = 'INSIGHT'
