export const AlertsEvents = {
  AlertsUsage: 'alerts_usage',
  ClickShareAlert: 'alerts_share',
  ClickCopyAlertLink: 'alerts_copy_link',
  ClickCopyAlert: 'alerts_copy',
  OpenAlert: 'alerts_open',
  ClickCreateAlert: 'alerts_create',
  ChangeAlertAbility: 'alerts_change_ability',
  ChangeAlertVisibility: 'alerts_change_visibility',
  ClickEditAlert: 'alerts_edit',
  SetAlertType: 'alerts_set_type',
  SetAlertAsset: 'alerts_set_asset',
  SetAlertWatchlist: 'alerts_set_watchlist',
  SetAlertScreener: 'alerts_set_screener',
  SetAlertAddress: 'alerts_set_address',
  SetAlertWalletAsset: 'alerts_set_address_asset',
  SetAlertSocialTrend: 'alerts_set_social',
  SetAlertMetric: 'alerts_set_metric',
  SetAlertCondition: 'alerts_set_condition',
  SetAlertChannel: 'alerts_set_channel',
  CreateAlert: 'alerts_save_new',
  EditAlert: 'alerts_save_old'
};